print("hello world")
print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print({'Marco_Antonio'})
print({'Cruz_Lopez'})
print({'Alejandra, Jose, Valentina'})
print({'mexico'})
print({'i_am_enjoy_python'})
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','python','Finland']))
print(type("Marco Antonio Cruz Lopez"))
print(type("Alejandra, Jose, Valentina"))
print(type("i_am_from_mexico"))